name: Seed build cache

on:
  push:
    branches:
      - '*'

jobs:
  ubuntu-code-style:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        jdk: [8, 11, 14]

    name: '${{ matrix.os }}, ${{ matrix.jdk }} seed build cache'
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: 'Set up JDK ${{ matrix.jdk }}'
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - uses: actions/cache@v2
        name: Cache ./gradle/caches/
        with:
          path: |
            ~/.gradle/caches/
          key: gradle-${{ runner.os }}-caches-${{ hashFiles('build.properties', '**/*.gradle.kts', 'gradle/wrapper/gradle-wrapper.properties') }}
      - name: Build pgjdbc
        env:
          S3_BUILD_CACHE_ACCESS_KEY_ID: ${{ secrets.S3_BUILD_CACHE_ACCESS_KEY_ID }}
          S3_BUILD_CACHE_SECRET_KEY: ${{ secrets.S3_BUILD_CACHE_SECRET_KEY }}
        run: ./gradlew --scan :linq4j:build -x test
